lib: [
  "_build/install/default/lib/Game/META"
  "_build/install/default/lib/Game/cards.ml"
  "_build/install/default/lib/Game/dune-package"
  "_build/install/default/lib/Game/game.a"
  "_build/install/default/lib/Game/game.cma"
  "_build/install/default/lib/Game/game.cmi"
  "_build/install/default/lib/Game/game.cmt"
  "_build/install/default/lib/Game/game.cmx"
  "_build/install/default/lib/Game/game.cmxa"
  "_build/install/default/lib/Game/game.ml"
  "_build/install/default/lib/Game/game__.cmi"
  "_build/install/default/lib/Game/game__.cmt"
  "_build/install/default/lib/Game/game__.cmx"
  "_build/install/default/lib/Game/game__.ml"
  "_build/install/default/lib/Game/game__Cards.cmi"
  "_build/install/default/lib/Game/game__Cards.cmt"
  "_build/install/default/lib/Game/game__Cards.cmx"
  "_build/install/default/lib/Game/opam"
]
libexec: [
  "_build/install/default/lib/Game/game.cmxs"
]
doc: [
  "_build/install/default/doc/Game/README.md"
]
